### ISSUE TITLE
`DescTools::Gini` function

### ISSUE THREAD

**Issue by simonedelsa** [CORE-forge/coresoi#20]
Just check about `DescTools::Gini`. Actually, it computes the Gini concentration measure of inequality on **NUMERICAL** variables, hence it cannot be used for indicator 5.

```r
set.seed(1234)
x <- sample(LETTERS[1:10], size=20, replace=TRUE)

tabx <- janitor::tabyl(x)
K <- nrow(tabx)

etermax <- (K-1)/K
eter <- (1-sum(tabx$percent^2))
eter_norm <- eter/etermax 
conc <- 1 - eter_norm #our final index of concentration (to be computed on the distribution of winners for each CA)

DescTools::Gini(tabx$n, unbiased=TRUE); ineq::Gini(tabx$n, corr=TRUE)
DescTools::Gini(tabx$n, unbiased=FALSE); ineq::Gini(tabx$n, corr=FALSE)
```

**Comment by giuliogcantone** [comment]
Before implementing a custom function, I want to be sure of something.

In DescTool there is index of heterogeneity called `GiniSimpsons`. This is the Gini-Simpson Index of heterogeneity for qualitative labels (indeed, it enforce a `factor` as its argument)

https://en.wikipedia.org/wiki/Diversity_index#Gini%E2%80%93Simpson_index

It is the value, not normalised over max, of the function proposed by Simone (which is great).

From what I understand, we normalise because it allows us to compare cases where exists a small range of non-zero labels (i.e. an agency that issues 5 contracts to a list of 3 $K$ winners) with cases with a bigger range of non-zero labels (100 contracts over $K$ 70 winners, yet possibly 1 winner won 20 contracts).

Yet the next passage confuses me,

$1 - \frac{x}{max(x)}$

is just the relative distance between $x$ and $max(x)$, or the distance between $x$ and $max(x)$ in $max(x)$ unit of measures.

Are we sure that this distance is a measure of _concentration_?

$max(x)$ is the most extreme heterogeneity given the number of classes ($K$). Do the high distance from this value imply concentration?

I will return on this later. It sounds for me but I want to be sure we are aligned on this measure.

**Comment by giuliogcantone** [comment]
Note:

I feel that my problem lies in the assumption of $K$ as a 'fixed' quantity for pre, and 'fixed' for post; while these are dynamics processes and $K$ behaves more as random value as if the $\hat{K}$ (pre, and post) are just sample value.

In the end, I am ok to adopt the proposed index since we only care about deviation from norm, but I see opportunity for future research notes on this normalised Gini-Simpson on "big data", especially for agencies with low $\hat{K}_{pre}$ and low $\hat{K}_{post}$, which are pretty common in the mock.

**Comment by giuliogcantone** [comment]
Memento:
Values are biased because `factor()` and `as_factor()` consider `NA` as a class.

Solution:
User or function should filter out `NA`  `{{winners}}`.
